### ISSUE TITLE
ava vs mocha

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/api-boilerplate#1]
Oliver uses [ava](https://github.com/avajs/ava) in a new project, I'm open to using new test framework but it's better to discuss with the team and keep it consistent.

/ping @Wiredcraft/core-members

**Comment by ole3021** [comment]
pros

- Minimal and fast
- Simple test syntax
- Runs tests concurrently
- Enforces writing atomic tests
- No implicit globals
- Includes TypeScript & Flow type definitions
- [Magic assert](#magic-assert)
- [Isolated environment for each test file](#process-isolation)
- [Write your tests in ES2017](#es2017-support)
- [Promise support](#promise-support)
- [Generator function support](#generator-function-support)
- [Async function support](#async-function-support)
- [Observable support](#observable-support)
- [Enhanced assertion messages](#enhanced-assertion-messages)
- [TAP reporter](#tap-reporter)
- [Automatic migration from other test runners](https://github.com/avajs/ava-codemods#migrating-to-ava)

**Comment by flyingant** [comment]
Could we have a real boilerplate project with basic config? That gonna be easy for us to take a look.

**Comment by xavierchow** [comment]
@flyingant This is supposed for backend, you can setup a new one for frontend.

**Comment by xavierchow** [comment]
For AVA, 
* Coverage setup is a bit messy.
* Can we use `only` or `skip` on a single test case?
* AVA is inspired from tape, not sure if other members are comfortable with its assert style.

**Comment by ChopperLee2011** [comment]
Personally, I do not care much about implicit globals, little performance improves in test cases. And most of other points @ole3021 mentions Mocha can also do.
But it is difficult for me to write tests without `before, after` hook, especially for APIs with DB operations, and also it is messy if you want to use Sinon. `Enforces writing atomic tests` is right thing but need too much effort to write every case atomic. So not agree to use AVA for our backend project, except it is a just very small lib without DB operations.

@xavierchow Ava support `only`

**Comment by wwayne** [comment]
We can use `only`, I like it's fast and `Enforces writing atomic tests`.

**BUT**(sorry Oliver), Personally, I prefer mocha just because it's more readable, I've used ava previously, maybe I was using it in a wrong way, but the test cases is not friendly for reading https://github.com/wwayne/mooseql/blob/master/test/schema.query.test.js

**Comment by ole3021** [comment]
@wwayne 

use chai with ava

```
import test from 'ava'

var assert = require('chai').assert
var expect = require('chai').expect
var should = require('chai').should()

test('expect with chai', t => {
  // typeof
  expect('test').to.be.a('string')
  expect({ foo: 'bar' }).to.be.an('object')
  expect(null).to.be.a('null')
  expect(undefined).to.be.an('undefined')
  expect(new Error).to.be.an('error')
  expect(new Float32Array()).to.be.a('float32array')
  expect(Symbol()).to.be.a('symbol')
})
```

lol

**Comment by ole3021** [comment]
@ChopperLee2011 

here is some code i use ava to do api baed test
```javascript
import test from 'ava'
import { axios } from '../_utils'

test('creat new special date', t => {
  const newSpecialDate = {
    title: '2017元旦',
    started: '2016-12-31T16:00:00.000Z',
    ended: '2017-01-01T16:00:00.000Z'
  }

  t.plan(4)

  return axios.post('/specialDate', newSpecialDate)
    .then(res => {
      t.is(res.status, 200)
      t.is(res.data.title, newSpecialDate.title)
      t.is(res.data.started, newSpecialDate.started)
      t.is(res.data.ended, newSpecialDate.ended)
    })
    .catch(err => t.fail(err.message))
})
```

share for future discuss.

**Comment by ole3021** [comment]
@flyingant for frontend i think [jest](https://facebook.github.io/jest/) is more suitable than ava?

**Comment by wwayne** [comment]
I meant using the format of Mocha is more readable to me, e.g.
```
describe('test an endpoint', () => {
   context('create', () => {
      it('test1')
      it('test2')
   })

   context('read', () => {
      ...
   })
})
```

**Comment by ole3021** [comment]
@wwayne  for that, that's the reason i don't want to use `mocha`

it's too much 'words' for me lol 😂

**Comment by wwayne** [comment]
@ole3021 拉黑取关，从此不是一路人
To be serious, I'd like using AVA in small project or one-developer-component, but mocha for team work because I think it would be easier for others to read and understand the test, just personal option.

**Comment by ole3021** [comment]
@wwayne 小拳拳锤你胸口

**Comment by xavierchow** [comment]
Let's stick to mocha for major projects, you can still use ava for side-projects for small libraries. Closing this for now.
