### ISSUE TITLE
Move nodemon config to package.json

### ISSUE THREAD

**Issue by paulvollmer** [Wiredcraft/api-boilerplate#13]
an idea to reduce the number of folders at the root directory could be to move the `nodemon` config to the `package.json`. see https://www.npmjs.com/package/nodemon#packagejson

the goal is to have less files at the root and most settings at the package.json.

**Comment by makara** [comment]
Well the idea is to allow people copy what they need and skip what they don't want, with less effort of editing files etc, so I still prefer more files.
