### ISSUE TITLE
lint json files

### ISSUE THREAD

**Issue by paulvollmer** [Wiredcraft/api-boilerplate#16]
### Context:
we have linter for the javascript `.js` files but we do not lint `.json` files

### Problem:
for example if there is an syntax error at a model json file, the loopback server fail to start.

### Solution: 
lint also the `.json` files at the `make lint` command

/cc @makara

**Comment by xavierchow** [comment]
FYI https://www.npmjs.com/package/jsonlint.

**Comment by paulvollmer** [comment]
i can add it to the Makefile and create a PR for it tomorrow

**Comment by paulvollmer** [comment]
`jsonlint` doesn't support wildcard/glob. the PR is still open. see here: https://github.com/zaach/jsonlint/pull/75

solution: we can fork the repo to wiredcraft gh org and use our fork as dependency.

**Comment by paulvollmer** [comment]
i fixed the directory issue for `zaach/jsonlint`. PR is out https://github.com/Wiredcraft/api-boilerplate/pull/21

**Comment by makara** [comment]
Hmm IMO

- Poorly formatted JS files don't break your system but are hard to read and that's why we needed a lint.
- Bad JSON files already break the tests and you don't really need another test to tell, do you?

**Comment by paulvollmer** [comment]
what if your tests only use for example `*.local.json` and there is an issue at a `*.production.json` file?

this was for me the reason to add a json linter to the test setup...

**Comment by paulvollmer** [comment]
merged
