### ISSUE TITLE
Add sentry integration

### ISSUE THREAD

**Issue by JuhaS** [Wiredcraft/api-boilerplate#34]
@paulvollmer can you implement a PR to have sentry integration.  At first it's ok if we just enable it in loopback which will batch errors in middleware and send events to sentry. 

Notice that if sentry key is missing it will just disable itself, so we don't have to implement logic to enable/disable the integration depending on if we have the sentry key or not.

**Comment by paulvollmer** [comment]
i found this at the raven nodejs-repo: https://github.com/getsentry/raven-node/blob/master/docs/integrations/loopback.rst

**Comment by makara** [comment]
@xavierchow Do you think we should do this?

**Comment by xavierchow** [comment]
No, I don't think sentry
