### ISSUE TITLE
[SUGGEST] Use jest replace mocha during the test

### ISSUE THREAD

**Issue by ole3021** [Wiredcraft/api-boilerplate#42]
I use just in some projects, and it works more elegance and easy than mocha.

So I would like to suggest we use `jest` in the boilerplate and out daily works.  

https://facebook.github.io/jest/

**Comment by makara** [comment]
Can you send me a PR?

**Comment by ole3021** [comment]
ok

**Comment by ole3021** [comment]
@paulvollmer we can work together to improve the PR

There are several things I am planning to add to the PR soon.

- [ ] Avoid Travis faile with coverall(By run coverage test in Travis after success)
- [ ] Use [Codecov](https://codecov.io/) replace the `coverall` we have now, to get better integration and visual report on each PR
- [ ] Define our test best practice, some point of my idea
  * Test should run by itself(without docker or other services), we should mock services and database APIs during our test
  * Test should be separate into Unit test(For some libs) and E2E test at least. and if we have time we also should do some integration test.
  * specify some libs we use generally during our test like `supertest`, `nock` and etc.

@makara  @paulvollmer how you think about this.

**Comment by paulvollmer** [comment]
> we can work together to improve the PR

sounds good, i'll check your PR

- switching to Codecov sounds good and hopeful it's more reliable then coveralls.

I'm not sure about:
> we should mock services and database APIs during our test
could be more complicated at real-world projects with more complex docker setups. then we need to mock a lot of databases/services. 

Some more questions to this topic:
- How can we mock different databases?
  - SQL
  - NoSQL
  - other like Redis , elasticsearch etc
- How do we integrate the mock database if we test with real data? for some projects, we run the `insert-data` script at the Travis-ci set up.


> Test should be separate into Unit test(For some libs) and E2E test 

sounds good to me. for this, I think we need to add a model to the API-boilerplate with basic CRUD endpoints. then we can have a best practice how to write the tests.

what about a `gh-pages` to document the API-boilerplate best practices. There we can do the recommended libs for mocking services, how to structure unit, E2E and integration tests and much more.

This can be helpful for all backend developers

**Comment by ole3021** [comment]
For Codecov, I used it sometimes and it does the job very well. but I just found it charges for private repos($2/each). But I think we can switch to Codecov on our public project.

**Comment by xavierchow** [comment]
closing ,no need to force everybody to use the same test framework, as long as it's aligned in one project.

**Comment by xavierchow** [comment]
BTW, I tried both mocha and jest, jest is good for TDD(jest watch is useful) but less support for mock, anyway both are good and solid.

**Comment by paulvollmer** [comment]
@xavierchow i'm using jest to mock also. for frontend the docs [here](https://jestjs.io/docs/en/mock-functions.html#mocking-modules) are useful if you need to mock api requests. in general i think the jest mock functions are quite powerful. But i never tried to use nock with jest.

**Comment by xavierchow** [comment]
yeah, jest mock is still powerful, I'm not comparing jest vs mocha, mocha has no mock support, I just compared jest mock with other dedicated mock modules (sinon.js, rewire, nock, etc.), of course, you can still use those npms with jest together, :D
