### ISSUE TITLE
Default log is too verbose

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/api-boilerplate#54]
It just overwhelms the test case description...
I'm gonna to set the default log as `file` instead of stdout.

<img width="1260" alt="screenshot 2018-07-17 15 03 46" src="https://user-images.githubusercontent.com/2748884/42801569-9fa8715a-89d2-11e8-91f1-3916ea2b2767.png">

cc @makara @ray @ChopperLee2011 @CCharlieLi

**Comment by CCharlieLi** [comment]
I think the point here is to see the details of what's happening when running test case which helpful to me. Making test looks clean and pretty is meaningless.

**Comment by xavierchow** [comment]
I will make it configurable.

**Comment by xavierchow** [comment]
Done with #55 , @CCharlieLi if you want to check the trace log via test cases, see: https://github.com/Wiredcraft/api-boilerplate#enable-verbose-trace-log.
