### ISSUE TITLE
Migrating to couchbase 5

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/api-boilerplate#57]
We are restricted to use the view instead of n1ql  due to scaling issue with couchbase3, 
but now the couhbase has been evolved to version 5 with a much more mature support for n1ql and other improvements, especially regarding the scale issue we can create multiple replicas of any index which I think should void the problem.

https://blog.couchbase.com/create-right-index-get-right-performance/

@pivstone was helpting to improve the [connector here](https://github.com/Wiredcraft/loopback-connector-couchbase3/pull/84), it's a good start, I'd like to hear team's voice, also I'm thinking of building a new connector for couchbase5 instead of revising the existing one.

@Wiredcraft/wiredcraft-backend-team 
@Wiredcraft/wiredcraft-devops-team

**Comment by pivstone** [comment]
Attach:

- @CCharlieLi has submitted a `couchbase5` branch for `authenticate` and  testing at Omni dev (correct me). 
- An alternative approach to practice N1QL via loopback mixin: https://github.com/Wiredcraft/omni-qr/blob/master/server/mixins/filter.js

**Comment by xavierchow** [comment]
Followed up with https://github.com/Wiredcraft/loopback-connector-couchbase3/pull/89, closing.
