### ISSUE TITLE
Why do we need debug stream serializer

### ISSUE THREAD

**Issue by haishanh** [Wiredcraft/api-boilerplate#6]
I still don't get the point why we do need this bunyan-debug-stream serializer

https://github.com/Wiredcraft/api-boilerplate/blob/0fa9471576fbd5a54b50ed6055de36ffe1507d3d/server/lib/loggers/debug.js#L1-L13

It seems we use this `lib.debug` just as we use the original [`debug`](https://github.com/visionmedia/debug) module. It's verbose and you can not turn it off, and those ANSI color string will make it harder for elasticsearch to tokenize strings.

I really think the original debug module and `syslog-bunyan-logger` logger pair is good enough.

- debug for verbose logging, which can be toggled on or off with `DEBUG`env var.
- syslog logger for sparse and key path logging, and not suppose to be turned off.

**Comment by xavierchow** [comment]
Totally agreed, debug is different from logging, don't mix them together.

**Comment by xavierchow** [comment]
I didn't get the point of using debug stream instead of npm `debug`, but as tackled here: https://github.com/Wiredcraft/api-boilerplate/issues/54, I changed the file stream for http trace log.
closing.
