### ISSUE TITLE
Trailing comma on multi-line

### ISSUE THREAD

**Issue by Elethom** [Wiredcraft/api-boilerplate#74]
Repo: https://github.com/Wiredcraft/eslint-config-wcl-backend

I recommend switching to `always-multiline`, as the reason follows:

Less clear:

```diff
 var foo = {
-    bar: "baz",
-    qux: "quux"
+    bar: "baz"
 };
```

More clear:

```diff
 var foo = {
     bar: "baz",
-    qux: "quux",
 };
```

Besides, editing would be much easier when you don't have to constantly add/remove commas.

Ref: https://eslint.org/docs/rules/comma-dangle

@Wiredcraft/wiredcraft-backend-team

**Comment by xavierchow** [comment]
Personally I don't like dangling comma, but I don't want to fire the argument about the code style again, there are always different options about it.
- http://www.davidarno.org/2016/03/23/trailing-commas-good-or-bad-practice-tldr-its-bad/
- https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

I'm gonna close this ticket and suggest the team to focus on the best practices such as test code/better logging/cleaner code, etc.
