### ISSUE TITLE
Avoid logging with `/health` API

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/api-boilerplate#76]
It's a request from @Wiredcraft/wiredcraft-devops-team , I guess the reason might be it's too verbose to have those logs in the production coz monitoring might keep calling this API?

We can defer the logging middleware to a later phase then it won't record the `/health` API.

**Comment by zbal** [comment]
Please defer to a later phase indeed - we don't need to get those `/health` logs captured (FYI it's being called every 2 sec by every load-balancer (traditionally each physical boxes) - AKA sometime all together up to 10+ hits per sec.
